ARG VARIANT=22-bookworm
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-${VARIANT}


ARG NPM_GLOBAL=/usr/local/share/npm-global
ARG PNPM_VERSION=10.2.1
ARG USERNAME=node
ARG GROUP=node

ENV NODE_ENV development
ENV NPM_GLOBAL ${NPM_GLOBAL}

# Add NPM global to PATH.
ENV PATH ${NPM_GLOBAL}/bin:${PATH}

RUN \
    # Configure global npm install location, use group to adapt to UID/GID changes
    if ! cat /etc/group | grep -e "^npm:" > /dev/null 2>&1; then groupadd -r npm; fi \
    && usermod -a -G ${GROUP} ${USERNAME} \
    && umask 0002 \
    && mkdir -p ${NPM_GLOBAL} \
    && touch /usr/local/etc/npmrc \
    && chown ${USERNAME}:${GROUP} ${NPM_GLOBAL} /usr/local/etc/npmrc \
    && chmod g+s ${NPM_GLOBAL} \
    && npm config -g set prefix ${NPM_GLOBAL} \
    && su ${USERNAME} -c "npm config -g set prefix $NPM_GLOBAL" \
    # Install eslint
    && su ${USERNAME} -c "umask 0002 && npm install -g eslint" \
    && npm cache clean --force > /dev/null 2>&1

# Install pnpm
RUN corepack enable
RUN corepack prepare pnpm@${PNPM_VERSION} --activate


WORKDIR /home/${USERNAME}/app

# Install pnpm project packages and copy source code into app
COPY --chown=${USERNAME}:${GROUP} pnpm-workspace.yaml package.json pnpm-lock.yaml ./
RUN pnpm install
COPY --chown=${USERNAME}:${GROUP} . .

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

CMD ["/bin/bash"]
EXPOSE 3000 8080